### ISSUE TITLE
Backport? 

### ISSUE THREAD

**Issue by Scarlaid** [MrSam7K/AutoComplete#2]
Maybe just 1.19.4 because it's somewhat a popular version till now, even though 1.20.1 already out for like months

I might not be the only one, so, if you could then thank you 🙏

**Comment by MrSam7K** [comment]
Mayhaps, it's not a big mod so not a big deal

**Comment by MrSam7K** [comment]
why did it not close lol, anyways yeah expect it to be on modrinth very soon
