### ISSUE TITLE
[Feature Request] Multilanguage Support.

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [MrSam7K/AutoComplete#3]
Hello!

It would be nice, if this mod could autocomplete words in other languages like Russian and etc.

**Comment by MrSam7K** [comment]
This is a great idea, thank you for it! I will try adding it, shouldn't be that hard :)

**Comment by MrSam7K** [comment]
Implemented in 4cbbff0, shortly will be available on modrinth
