### ISSUE TITLE
[Suggestion] Allow selecting multiple languages at the same time

### ISSUE THREAD

**Issue by thecatcore** [MrSam7K/AutoComplete#4]

**Comment by MrSam7K** [comment]
> _No description provided._

Sure, that sounds like a good idea :)

**Comment by MrSam7K** [comment]
> Sorry for the off-top message, but I wonder where You've got words (I know that You contain that lists in data/AutoComplete repo, but... where are these DBs for language autocompleting?) for AutoComplete's db?

I just find them online really

**Comment by MrSam7K** [comment]
implemented in [this commit](https://github.com/MrSam7K/AutoComplete/commit/aedfb2536e96eb7448aa0619637eeb730387c1e3)
