### ISSUE TITLE
1.20.6 and 1.21

### ISSUE THREAD

**Issue by itsarian** [MrSam7K/AutoComplete#7]
any plans to update to 1.20.6 and 1.21?

**Comment by MrSam7K** [comment]
ofcourse, when I'll find free time I'll update it ;)

**Comment by itsarian** [comment]
any updates?

**Comment by MrSam7K** [comment]
as referenced above I updated the mod to both major versions :) they are available on [modrinth](https://modrinth.com/mod/autocomplete)
